events {
    worker_connections 1024;
}

http {
    # --------------------------------------------------------
    # 🧠 CLÚSTER DE IA (Tus 3 máquinas físicas corriendo Ollama)
    # --------------------------------------------------------
    upstream ollama_cluster {
        # ¡IMPORTANTE! Cambia estas IPs por las IPs locales reales de tus 3 computadoras
        server 192.168.50.33:11434; # IP del Nodo 1
        server 192.168.50.83:11434; # IP del Nodo 2
        server 192.168.50.19:11434; # IP del Nodo 3
    }

    # --------------------------------------------------------
    # 💻 TU BACKEND (El contenedor de Node.js)
    # --------------------------------------------------------
    upstream backend_app {
        # "backend" es el nombre del servicio que pusimos en el docker-compose
        server app_documentos:3000;
    }

    server {
        listen 80;

        location /api/generate {
            proxy_pass http://ollama_cluster;
            proxy_set_header Host $host;
            proxy_read_timeout 300s; 
            proxy_connect_timeout 75s;

            add_header X-Nodo-IA $upstream_addr always;
        }

        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;

            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;

        }
    }
}